### ISSUE TITLE
Lay on Hands: No Permission to remove effects

### ISSUE THREAD

**Issue by adotor** [Maselkov/masels-foundryvtt-macros#1]
When using the lay on hands macro to remove conditions like poisoned and diseased, it is necessary to be a GM to use the function 
`MidiQOL.socket().functions.get("removeEffects")`. Player receive an error message.

**Comment by Maselkov** [comment]
This seems to be the case. i thought those functions were there for that, and I am also pretty sure that it worked once upon a time, ha. Seems like callback macros are the only solution, unless there are other functions that I'm missing?

**Comment by adotor** [comment]
Advanced Macros has a Run as GM setting, but there a restrictions about ownership and it seems impossible to toggle this option on an ItemMacro.

**Comment by Maselkov** [comment]
I found out about 
```js
MidiQOL.socket().executeAsGM()
```
now. I went ahead and updated the macro, though I haven't tested it yet. It should work with non-gm clients now.
