### ISSUE TITLE
Setting up Divine Smite

### ISSUE THREAD

**Issue by Apocalyptichobo** [Maselkov/masels-foundryvtt-macros#2]
How do I use divine smite?

**Comment by Maselkov** [comment]
Make an item under the Features, put this code in the item macro, and add itemmacro to the on use macro. This should about cover it. Let me know if this works, or if any issues are encountered. Recent foundry updates might have broken some things, and I haven't gotten around to updating them

**Comment by Maselkov** [comment]
Assume its solved
